// Angular8/quantum-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from './data.service';
import { Class } from './model/class';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  classes;

  modalClass: Class = new Class(0, '', '', '');

  constructor(private data: DataService) { }

  ngOnInit(): void {
    this.data.getClasses().subscribe(
      data => {
        this.classes = data;
        console.log(data);
      }
    );
  }

  newClass() {
    this.modalClass = new Class(0, '', '', '');
  }

  editClass(item: Class) {
    this.modalClass = item;
    this.data.editClass(item).subscribe(
      data => {
        console.log('data updated: ' + data);
      }
    );
  }

  submitClassForm(value) {
    console.log(value);
    if (value.id == 0) {
      console.log('new');
      this.data.addClass(value).subscribe(
        data => {
          this.classes.push(data);
          this.modalClass = new Class(0, '', '', '');
        }
      );
    } else {
      console.log('edit');
      this.data.editClass(value).subscribe(
        data=> {
          console.log('class updated: ' + JSON.stringify(data));
        }
      );
    }
  }

  deleteClass(id) {
    console.log('Class: ' + id + ' deleted');
    this.data.deleteClass(id).subscribe(
      _=>{
        this.classes = this.classes.filter(t=>t.id!==id);
      }
    );
  }
}

<div class="container">
  <h1>Quantum Uni</h1>
  <h4>Class <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#classModal"
      (click)="newClass()">
      New
    </button></h4>

  <!-- Modal -->
  <div class="modal fade" id="classModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" *ngIf="modalClass.id==0">New Class</h5>
          <h5 class="modal-title" *ngIf="modalClass.id!=0">Edit Class</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form #classForm="ngForm" (ngSubmit)="submitClassForm(classForm.value)" novalidate>
            <div class="form-group">
              <label>Class name</label>
              <input type="text" class="form-control" name="className" [(ngModel)]="modalClass.className" required>
            </div>
            <div class="form-group">
              <label>Location</label>
              <input type="text" class="form-control" name="location" [(ngModel)]="modalClass.location" required>
            </div>

            <div class="form-group">
              <label>Teacher</label>
              <input type="text" class="form-control" name="teacher" [(ngModel)]="modalClass.teacher" required>
            </div>

            <input name="id" [ngModel]="modalClass.id" style="display: none;">

            <button type="submit" class="btn btn-outline-success btn-sm" onclick="$('#classModal').modal('hide')">Save</button>

          </form>
        </div>

      </div>
    </div>
  </div>

  <div *ngIf="classes">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Location</th>
          <th scope="col">Teacher Name</th>
          <th scope="col">Op</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let class of classes">

          <td><a routerLink="/student/{{class.id}}">{{class.className}}</a></td>
          <td>{{class.location}}</td>
          <td>{{class.teacher}}</td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#classModal"
                (click)="editClass(class)">Edit</button>
              <button type="button" class="btn btn-outline-danger btn-sm" (click)="deleteClass(class.id)">Delete</button>
            </div>
          </td>
        </tr>

      </tbody>
    </table>
  </div>
  <router-outlet></router-outlet>
</div>

// React/reactstrap/quantum-app/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';
import {
  ButtonGroup, Button, Table, Modal,
  ModalHeader, ModalBody, ModalFooter,
  Form, FormGroup, Label, Input
} from 'reactstrap';

function App() {

  const [modal, setModal] = useState(false);
  const [data, setData] = useState({ classes: [], students: [] });

  const [id, setId] = useState(0);
  const [classname, setClassname] = useState('');
  const [location, setLocation] = useState('');
  const [teacher, setTeacher] = useState('');

  useEffect(() => {
    fetch('https://quantumit.azurewebsites.net/Class')
      .then(res => res.json())
      .then(
        result => {
          setData({ classes: result, students: [] });
        }
      );
  }, []);

  const toggle = () => {
    setModal(!modal);
  }

  const handleAdd = () => {
    setId(0);
    setClassname('');
    setLocation('');
    setTeacher('');
    setModal(true);
  }

  const handleEdit = (item) => {
    setId(item.id);
    setClassname(item.className);
    setLocation(item.location);
    setTeacher(item.teacher);
    setModal(true);
  }

  function handleDelete(id) {
    console.log('The delete was clicked.' + id);
    fetch('https://quantumit.azurewebsites.net/Class/' + id, {
      method: 'DELETE'
    })
      .then(res => res.text())
      .then(result => {
        console.log('Deleted');
        let newClasses = data.classes.filter(t => t.id !== id);
        setData({ classes: newClasses, students: [] })
      });

  }

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(id + ' ' + classname + ' ' + location + ' ' + teacher);

    if (id == 0)
      addClass({ className: classname, location: location, teacher: teacher });
    else
      editClass({ id: id, className: classname, location: location, teacher: teacher });

    setModal(false);
  }

  const editClass = (opts) => {
    console.log('Edit the Class');

    fetch('https://quantumit.azurewebsites.net/Class', {
      method: 'PUT',
      body: JSON.stringify(opts),
      headers: {
        'Content-Type': 'application/json'
      }
    })
      .then(res => res.json())
      .then(
        result => {
          
        }
      );
  }

  const addClass = (opts) => {

    fetch('https://quantumit.azurewebsites.net/Class', {
      method: 'POST',
      body: JSON.stringify(opts),
      headers: {
        'Content-Type': 'application/json'
      }
    })
      .then(res => res.json())
      .then(
        result => {
          setData({ classes: [...data.classes, result], students: [] })
        }
      );
  }

  return (
    <div className="container">
      <h2>Class <Button color="outline-primary" className="btn-sm" onClick={handleAdd}>Add</Button></h2>

      <Table>
        <thead>
          <tr>
            <th>Class name</th>
            <th>Location</th>
            <th>Teacher Name</th>
            <th>Op</th>
          </tr>
        </thead>
        <tbody>
          {data.classes.map(item => (
            <tr key={item.id}>
              <th scope="row">{item.className}</th>
              <td>{item.location}</td>
              <td>{item.teacher}</td>
              <td><ButtonGroup>
                <Button color="outline-info" className="btn-sm" onClick={() => handleEdit(item)}>Edit</Button>
                {/* <Button color="danger" onClick={(e) => { e.preventDefault(); handleDelete(item.id) }}>Delete</Button> */}
                <Button color="outline-danger" className="btn-sm" onClick={() => handleDelete(item.id)}>Delete</Button>
                {/* <Button color="danger" onClick={handleDelete}>Delete</Button> */}
              </ButtonGroup></td>
            </tr>
          ))}
        </tbody>
      </Table>

      <Modal isOpen={modal} toggle={toggle}>
        <ModalHeader toggle={toggle}>Edit Class</ModalHeader>
        <ModalBody>

          <Form onSubmit={handleSubmit}>
            <FormGroup>
              <Label>Class name</Label>
              <Input type="text" name="className"
                value={classname}
                onChange={(e) => { setClassname(e.target.value) }} />
            </FormGroup>
            <FormGroup>
              <Label>Location</Label>
              <Input type="text" name="location"
                value={location}
                onChange={(e) => { setLocation(e.target.value) }} />
            </FormGroup>
            <FormGroup>
              <Label>Teacher</Label>
              <Input type="text" name="teacher"
                value={teacher}
                onChange={(e) => { setTeacher(e.target.value) }} />
            </FormGroup>

            <Button color="outline-success" className="btn-sm">Submit</Button>{''}
          </Form>

        </ModalBody>

      </Modal>
    </div>
  );
}

export default App;
