// React/reactstrap/quantum-app/src/components/Student.js
import React, { useState, useEffect } from 'react';
import {
    ButtonGroup, Button, Table, Modal,
    ModalHeader, ModalBody, ModalFooter,
    Form, FormGroup, Label, Input
} from 'reactstrap';

const Student = ({ classId }) => {
    const [modal, setModal] = useState(false);
    const [students, setStudents] = useState([]);

    const [id, setId] = useState(0);
    const [fname, setFname] = useState('');
    const [lname, setLname] = useState('');
    const [age, setAge] = useState(0);
    const [gpa, setGpa] = useState(0);

    const toggle = () => {
        setModal(!modal);
    }

    const handleAdd = () => {
        setId(0);
        setFname('');
        setLname('');
        setAge(0);
        setGpa(0);
        setModal(true);
    }

    const handleEdit = (item) => {
        console.log('edit ' + item.id);
        setId(item.id);
        setFname(item.fName);
        setLname(item.lName);
        setAge(item.age);
        setGpa(item.gpa);
        setModal(true);
    }

    const handleDelete = (id) => {
        console.log('The delete was clicked.' + id);
        fetch('https://quantumit.azurewebsites.net/Student/' + id, {
            method: 'DELETE'
        })
            .then(res => res.text())
            .then(result => {
                console.log('Deleted');
                let newStudents = students.filter(t => t.id !== id);
                setStudents(newStudents);
            });
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log('form submitted');
        console.log(id + ' ' + fname + ' ' + lname + ' ' + age + ' ' + gpa);
        let data = { id: id, fName: fname, lName: lname, age: age, gpa: gpa, classId: classId };

        if (id == 0) {
            addStudent(data);
        } else {
            editStudent(data);
        }

        setModal(false);
    }

    const editStudent = (opts) => {
        fetch('https://quantumit.azurewebsites.net/Student', {
            method: 'PUT',
            body: JSON.stringify(opts),
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(res => res.json())
            .then(
                result => {
                    let returnStudents = [...students];
                    returnStudents[students.findIndex(x => x.id == opts.id)] = opts;
                    setStudents(returnStudents);
                }
            );

    }

    const addStudent = (opts) => {
        fetch('https://quantumit.azurewebsites.net/Student', {
            method: 'POST',
            body: JSON.stringify(opts),
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(res => res.json())
            .then(
                result => {
                    setStudents([...students, result]);
                }
            );
    }

    useEffect(() => {
        fetch('https://quantumit.azurewebsites.net/Student/class/' + classId)
            .then(res => res.json())
            .then(
                result => {
                    setStudents(result);
                }
            );
    }, []);

    return (<div>

        {students.length > 0 ?
            <Table>
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Age</th>
                        <th>GPA</th>
                        <th>Op</th>
                    </tr>
                </thead>
                <tbody>
                    {
                        students.map(item => (
                            <tr key={item.id}>
                                <td>{item.fName} {item.lName}</td>
                                <td>{item.age}</td>
                                <td>{item.gpa}</td>
                                <td>
                                    <ButtonGroup>
                                        <Button color="outline-info" className="btn-sm" onClick={() => handleEdit(item)}>Edit</Button>
                                        <Button color="outline-danger" className="btn-sm" onClick={() => handleDelete(item.id)}>Delete</Button>
                                    </ButtonGroup>
                                </td>
                            </tr>
                        ))
                    }
                </tbody>
            </Table>
            : <div>No student registered.</div>}
        <Button color="outline-primary" className="btn-sm" onClick={handleAdd}>Add</Button>
        <Modal isOpen={modal} toggle={toggle}>
            <ModalHeader toggle={toggle}>Edit Class</ModalHeader>
            <ModalBody>
                <h2>Form</h2>
                <Form onSubmit={handleSubmit}>
                    <FormGroup>
                        <Label>First Name</Label>
                        <Input type="text" name="fName"
                            value={fname} onChange={(e) => { setFname(e.target.value) }} />
                    </FormGroup>
                    <FormGroup>
                        <Label>Last Name</Label>
                        <Input type="text" name="lName"
                            value={lname} onChange={(e) => { setLname(e.target.value) }} />
                    </FormGroup>
                    <FormGroup>
                        <Label>Age</Label>
                        <Input type="text" name="age"
                            value={age} onChange={(e) => { setAge(e.target.value) }} />
                    </FormGroup>
                    <FormGroup>
                        <Label>GPA</Label>
                        <Input type="text" name="gpa"
                            value={gpa} onChange={(e) => { setGpa(e.target.value) }} />
                    </FormGroup>
                    <Button color="outline-success" className="btn-sm">Submit</Button>{''}
                </Form>
            </ModalBody>
        </Modal>
    </div>)
}

export default Student;

// Angular8/quantum-app/src/app/student/student.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { DataService } from '../data.service';
import { Student } from '../model/student';
import { Class } from '../model/class';

@Component({
  selector: 'app-student',
  templateUrl: './student.component.html',
  styleUrls: ['./student.component.css']
})
export class StudentComponent implements OnInit {

  classId: number;
  currentClass: Class;
  students: Student[] = [];
  private sub: any;
  modalStudent: Student = new Student(0, '', '', 0, 0, 0);

  constructor(private route: ActivatedRoute, private data: DataService) { }

  ngOnInit(): void {
    this.sub = this.route.params.subscribe(params => {
      this.classId = +params['id'];
      this.data.getStudentByClass(this.classId).subscribe(
        data => {
          this.students = data;
          console.log(data);
        }
      );

      this.data.getClass(this.classId).subscribe(
        data => {
          this.currentClass = data;
        }
      );
    });
  }

  ngOnDestroy() {
    this.sub.unsubscribe();
  }

  newStudent() {
    this.modalStudent = new Student(0, '', '', 0, 0, 0);
  }

  editStudent(item: Student){
    this.modalStudent = item;
    console.log('item');
  }

  submitStudentForm(value){
    console.log(value);
    value.gpa = +value.gpa;

    if(value.id==0){
      console.log('new student');
      value.classId = this.classId;
      
      console.log(value);

      this.data.addStudent(value).subscribe(
        data=> {
          this.students.push(data);
          this.modalStudent = new Student(0, '', '', 0, 0, 0);
        }
      );

    }else {
      console.log('edit student');
      this.data.editStudent(value).subscribe(
        data=>{
          console.log('student updated: ' + JSON.stringify(data));
        }
      );
    }
  }

  deleteStudent(id) {
    console.log('Student: ' + id + ' deleted');
    this.data.deleteStudent(id).subscribe(
      _=>{
        this.students= this.students.filter(t=>t.id!==id);
      }
    );
  }
}


<div *ngIf="students?.length > 0">
    <h4>Students at {{currentClass.className}} <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#studentModal"
        (click)="newStudent()">
        New
      </button></h4>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Student Name</th>
                <th scope="col">Age</th>
                <th scope="col">GPA</th>
                <th scope="col">Op</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let student of students">

                <td><span [class.text-success]="student.gpa>3.2">{{student.fName}} {{student.lName}}</span></td>
                <td>{{student.age}}</td>
                <td>{{student.gpa}}</td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-outline-primary btn-sm" 
                            data-toggle="modal" data-target="#studentModal" (click)="editStudent(student)">Edit</button>
                        <button type="button" class="btn btn-outline-danger btn-sm" (click)="deleteStudent(student.id)">Delete</button>
                    </div>
                </td>
            </tr>

        </tbody>
    </table>
</div>
<div *ngIf="students?.length <= 0">
    <p>No students in the current Class. <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#studentModal"
        (click)="newStudent()">
        New
      </button></p>
</div>

<!-- Modal -->
<div class="modal fade" id="studentModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" *ngIf="modalStudent.id==0">New Student</h5>
          <h5 class="modal-title" *ngIf="modalStudent.id!=0">Edit Student</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form #studentForm="ngForm" (ngSubmit)="submitStudentForm(studentForm.value)" novalidate>
            <div class="form-group">
              <label>First Name</label>
              <input type="text" class="form-control" name="fName" [(ngModel)]="modalStudent.fName" required>
            </div>
            <div class="form-group">
              <label>Last Name</label>
              <input type="text" class="form-control" name="lName" [(ngModel)]="modalStudent.lName" required>
            </div>
            <div class="form-group">
              <label>Age</label>
              <input type="number" class="form-control" name="age" [(ngModel)]="modalStudent.age" required>
            </div>

            <div class="form-group">
              <label>GPA</label>
              <input type="text" class="form-control" name="gpa" [(ngModel)]="modalStudent.gpa" required>
            </div>

            <input name="id" [ngModel]="modalStudent.id" style="display: none;">
            <input name="classId" [ngModel]="modalStudent.classId" style="display: none;">

            <button type="submit" class="btn btn-outline-success btn-sm" onclick="$('#studentModal').modal('hide')">Save</button>

          </form>
        </div>

      </div>
    </div>
  </div>
